"""Seed the database with 25 real Glasgow businesses."""

import asyncio
from datetime import datetime

from app.database import init_db, async_session
from app.models.insurer import Insurer
from app.models.building import Building
from app.models.snapshot import Snapshot
from app.models.evidence_item import EvidenceItem


BUILDINGS = [
    {
        "address": "145 St Vincent Street, Glasgow G2 5JF",
        "tenant": "Di Maggio's Restaurants (Glasgow Fort) Ltd",
        "risk_score": 42,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Restaurant",
        "property_class": "Restaurant",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Italian Restaurant",
        "use_mismatch": False,
        "lat": 55.8615,
        "lng": -4.2555,
        "assigned_to": None,
        "signals": [
            {
                "source": "Council Rates",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Rateable value under review following seating area expansion",
                "timestamp": "2026-03-14T10:00:00Z",
            },
            {
                "source": "Fire Service",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "Kitchen extraction system maintenance due within 30 days",
                "timestamp": "2026-03-10T14:30:00Z",
            },
        ],
    },
    {
        "address": "169 West George Street, Glasgow G2 2LB",
        "tenant": "Consilium Chartered Accountants",
        "risk_score": 18,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Accountancy Practice",
        "use_mismatch": False,
        "lat": 55.8625,
        "lng": -4.2575,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "All compliance documents current — fully compliant",
                "timestamp": "2026-03-14T09:00:00Z",
            },
        ],
    },
    {
        "address": "227 West George Street, Glasgow G2 2ND",
        "tenant": "Baron (Glasgow) Ltd",
        "risk_score": 58,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Bar",
        "property_class": "Bar",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Wine Bar / Late Night Venue",
        "use_mismatch": True,
        "lat": 55.8630,
        "lng": -4.2580,
        "assigned_to": "me",
        "signals": [
            {
                "source": "Vision Model",
                "type": "cv_classification",
                "severity": "medium",
                "weight": 40,
                "description": "Late trading hours observed — operating beyond licensed hours",
                "timestamp": "2026-03-14T02:15:00Z",
            },
            {
                "source": "Licensing Board",
                "type": "licensing",
                "severity": "medium",
                "weight": 20,
                "description": "Alcohol license renewal pending — temporary permissions in place",
                "timestamp": "2026-03-12T11:00:00Z",
            },
        ],
    },
    {
        "address": "474 Dumbarton Road, Clydebank G81 4DN",
        "tenant": "Glasgow Pubs Ltd",
        "risk_score": 35,
        "risk_tier": "low",
        "status": "monitoring",
        "property_type": "Pub",
        "property_class": "Pub",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Traditional Public House",
        "use_mismatch": False,
        "lat": 55.9000,
        "lng": -4.4050,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "low",
                "weight": 40,
                "description": "Listed building facade in good condition — minor repointing required",
                "timestamp": "2026-03-13T10:00:00Z",
            },
        ],
    },
    {
        "address": "22 Montrose Street, Glasgow G1 1RE",
        "tenant": "G1 (Glasgow) Electricians Ltd",
        "risk_score": 28,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": True,
        "registered_use": "Class 4 — Business",
        "detected_use": "Electrical Services Office",
        "use_mismatch": False,
        "lat": 55.8605,
        "lng": -4.2425,
        "assigned_to": None,
        "signals": [
            {
                "source": "Companies House",
                "type": "sic_mismatch",
                "severity": "low",
                "weight": 25,
                "description": "Company filing up to date — all returns submitted on time",
                "timestamp": "2026-03-11T09:00:00Z",
            },
        ],
    },
    {
        "address": "115 Bath Street, Glasgow G2 2SZ",
        "tenant": "Office Glasgow Ltd",
        "risk_score": 22,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Serviced Office Provider",
        "use_mismatch": False,
        "lat": 55.8635,
        "lng": -4.2550,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "Fire safety certificate valid — next inspection due Q4 2026",
                "timestamp": "2026-03-10T10:00:00Z",
            },
        ],
    },
    {
        "address": "257 Gallowgate, Glasgow G4 0TP",
        "tenant": "Bar 67 Glasgow Ltd",
        "risk_score": 71,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Bar",
        "property_class": "Bar",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Music Venue / Bar",
        "use_mismatch": True,
        "lat": 55.8560,
        "lng": -4.2365,
        "assigned_to": "me",
        "signals": [
            {
                "source": "Vision Model",
                "type": "cv_classification",
                "severity": "high",
                "weight": 40,
                "description": "Live music venue operation detected — entertainment license may be required",
                "timestamp": "2026-03-14T23:30:00Z",
            },
            {
                "source": "Environmental Health",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Noise complaints from adjacent residential properties",
                "timestamp": "2026-03-09T15:00:00Z",
            },
            {
                "source": "Fire Service",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Occupancy levels during events may exceed fire safety limits",
                "timestamp": "2026-03-05T12:00:00Z",
            },
        ],
    },
    {
        "address": "407 Clarkston Road, Muirend, Glasgow G44 3LL",
        "tenant": "The Carpet Shop Glasgow Ltd",
        "risk_score": 19,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Carpet & Flooring Retail",
        "use_mismatch": False,
        "lat": 55.8170,
        "lng": -4.2700,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "All compliance documents verified — low risk classification",
                "timestamp": "2026-03-08T11:00:00Z",
            },
        ],
    },
    {
        "address": "545 Cathcart Road, Glasgow G42 8SG",
        "tenant": "Office Direct Glasgow Ltd",
        "risk_score": 45,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Office/Retail",
        "property_class": "Mixed Use",
        "listed": False,
        "registered_use": "Class 4 — Business / Class 1 — Retail",
        "detected_use": "Office Supplies & Furniture Showroom",
        "use_mismatch": False,
        "lat": 55.8370,
        "lng": -4.2620,
        "assigned_to": None,
        "signals": [
            {
                "source": "Council Rates",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Mixed-use classification review required — potential underpayment",
                "timestamp": "2026-03-12T14:00:00Z",
            },
        ],
    },
    {
        "address": "587 Dumbarton Road, Glasgow G11 6HY",
        "tenant": "Millies Coffee Shop (Glasgow) Ltd",
        "risk_score": 33,
        "risk_tier": "low",
        "status": "monitoring",
        "property_type": "Café",
        "property_class": "Café",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Coffee Shop",
        "use_mismatch": False,
        "lat": 55.8720,
        "lng": -4.3050,
        "assigned_to": None,
        "signals": [
            {
                "source": "Council Planning",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "Planning permission for outdoor seating submitted — awaiting decision",
                "timestamp": "2026-03-11T09:30:00Z",
            },
        ],
    },
    {
        "address": "3 Gordon Street, Glasgow G1 3PL",
        "tenant": "Shop Local Glasgow Ltd",
        "risk_score": 26,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Convenience Store / Newsagent",
        "use_mismatch": False,
        "lat": 55.8595,
        "lng": -4.2500,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "low",
                "weight": 40,
                "description": "Listed building in good condition — Category B, no concerns",
                "timestamp": "2026-03-13T10:00:00Z",
            },
        ],
    },
    {
        "address": "14 Newton Place, Glasgow G3 7PY",
        "tenant": "MM Restaurant Glasgow Ltd",
        "risk_score": 67,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Restaurant",
        "property_class": "Restaurant",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Multi-cuisine Restaurant",
        "use_mismatch": False,
        "lat": 55.8650,
        "lng": -4.2750,
        "assigned_to": "me",
        "signals": [
            {
                "source": "Health & Safety",
                "type": "keyword_hit",
                "severity": "high",
                "weight": 15,
                "description": "Food hygiene rating pending re-inspection — previous rating was 2",
                "timestamp": "2026-03-14T09:00:00Z",
            },
            {
                "source": "Companies House",
                "type": "sic_mismatch",
                "severity": "medium",
                "weight": 25,
                "description": "Recent company director changes — new controlling interest",
                "timestamp": "2026-03-10T11:00:00Z",
            },
            {
                "source": "Council Rates",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Business rates relief application submitted — under review",
                "timestamp": "2026-03-06T14:00:00Z",
            },
        ],
    },
    {
        "address": "66 Langlands Road, Glasgow G51 3BQ",
        "tenant": "Bargain Store Glasgow Ltd",
        "risk_score": 38,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Discount Retail Store",
        "use_mismatch": False,
        "lat": 55.8530,
        "lng": -4.2850,
        "assigned_to": None,
        "signals": [
            {
                "source": "Fire Service",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Fire exit signage requires updating — minor non-compliance noted",
                "timestamp": "2026-03-09T13:00:00Z",
            },
        ],
    },
    {
        "address": "272 Bath Street, Glasgow G2 4JR",
        "tenant": "Best Bar Glasgow Ltd",
        "risk_score": 44,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Bar",
        "property_class": "Bar",
        "listed": True,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Cocktail Bar",
        "use_mismatch": False,
        "lat": 55.8640,
        "lng": -4.2600,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "medium",
                "weight": 40,
                "description": "Internal alterations for bar layout — may require listed building consent",
                "timestamp": "2026-03-12T10:00:00Z",
            },
        ],
    },
    {
        "address": "153 Queen Street, Glasgow G1 3BJ",
        "tenant": "The Glasgow Body Shop Ltd",
        "risk_score": 29,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Beauty & Cosmetics Retail",
        "use_mismatch": False,
        "lat": 55.8590,
        "lng": -4.2500,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "All product safety certifications current — compliant with regulations",
                "timestamp": "2026-03-11T09:00:00Z",
            },
        ],
    },
    {
        "address": "135 Garscadden Road, Glasgow G15 6UQ",
        "tenant": "Glasgow Food Shop Ltd",
        "risk_score": 52,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail (Grocery)",
        "detected_use": "Convenience Store with Hot Food",
        "use_mismatch": True,
        "lat": 55.9150,
        "lng": -4.3650,
        "assigned_to": None,
        "signals": [
            {
                "source": "Vision Model",
                "type": "cv_classification",
                "severity": "medium",
                "weight": 40,
                "description": "Hot food preparation area detected — may require additional licensing",
                "timestamp": "2026-03-13T14:00:00Z",
            },
            {
                "source": "Environmental Health",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Food hygiene certificate approaching expiry — renewal required",
                "timestamp": "2026-03-10T11:00:00Z",
            },
        ],
    },
    {
        "address": "37 Bath Street, Glasgow G2 1HW",
        "tenant": "The Eggless Cake Shop Glasgow Ltd",
        "risk_score": 25,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Specialist Bakery",
        "use_mismatch": False,
        "lat": 55.8635,
        "lng": -4.2555,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "low",
                "weight": 40,
                "description": "Listed building facade maintained — excellent condition",
                "timestamp": "2026-03-14T10:00:00Z",
            },
        ],
    },
    {
        "address": "Unit 5, 70 Strathclyde Street, Glasgow G40 4JR",
        "tenant": "Glasgow Aluminium Shop Fronts Ltd",
        "risk_score": 41,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Industrial/Trade",
        "property_class": "Industrial",
        "listed": False,
        "registered_use": "Class 5 — General Industrial",
        "detected_use": "Shop Front Manufacturing",
        "use_mismatch": False,
        "lat": 55.8480,
        "lng": -4.2150,
        "assigned_to": None,
        "signals": [
            {
                "source": "Health & Safety",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Workshop machinery safety inspection due — scheduled for next month",
                "timestamp": "2026-03-12T09:00:00Z",
            },
        ],
    },
    {
        "address": "21 Elmbank Street, Glasgow G2 4PB",
        "tenant": "Glasgow Scout Shop Ltd",
        "risk_score": 15,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Charity / Non-profit Retail",
        "use_mismatch": False,
        "lat": 55.8630,
        "lng": -4.2650,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "Charity status confirmed — rates exemption in place",
                "timestamp": "2026-03-13T10:00:00Z",
            },
        ],
    },
    {
        "address": "95 Saltmarket, Glasgow G1 5LE",
        "tenant": "Glasgow ShopSmart Ltd",
        "risk_score": 36,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "General Merchandise Store",
        "use_mismatch": False,
        "lat": 55.8545,
        "lng": -4.2430,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "low",
                "weight": 40,
                "description": "Category B listed building — minor facade repairs required",
                "timestamp": "2026-03-11T10:00:00Z",
            },
        ],
    },
    {
        "address": "78 Main Street, Cambuslang, Glasgow G72 7EP",
        "tenant": "Local Shop Glasgow Ltd",
        "risk_score": 24,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Neighborhood Convenience Store",
        "use_mismatch": False,
        "lat": 55.8190,
        "lng": -4.1670,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "All compliance documents current — low risk",
                "timestamp": "2026-03-14T09:00:00Z",
            },
        ],
    },
    {
        "address": "254 Main Street, Bellshill, Glasgow G74 1AB",
        "tenant": "Shopping Planet Glasgow Ltd",
        "risk_score": 47,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Online Retail with Collection Point",
        "use_mismatch": True,
        "lat": 55.8160,
        "lng": -4.0250,
        "assigned_to": None,
        "signals": [
            {
                "source": "Council Rates",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Mixed online/offline operation — rateable value assessment pending",
                "timestamp": "2026-03-12T14:00:00Z",
            },
        ],
    },
    {
        "address": "8 Righead Gate, East Kilbride, Glasgow G74 1LS",
        "tenant": "Orange Shop Glasgow Ltd",
        "risk_score": 31,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Mobile Phone & Electronics Retail",
        "use_mismatch": False,
        "lat": 55.7650,
        "lng": -4.1750,
        "assigned_to": None,
        "signals": [
            {
                "source": "Routine Check",
                "type": "keyword_hit",
                "severity": "low",
                "weight": 15,
                "description": "Electrical safety certificates valid — compliant",
                "timestamp": "2026-03-13T11:00:00Z",
            },
        ],
    },
    {
        "address": "29 Parkholm Drive, Glasgow G53 7WQ",
        "tenant": "Shop & Stop Glasgow Ltd",
        "risk_score": 43,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Automated Convenience Store",
        "use_mismatch": False,
        "lat": 55.8330,
        "lng": -4.3450,
        "assigned_to": None,
        "signals": [
            {
                "source": "Vision Model",
                "type": "cv_classification",
                "severity": "medium",
                "weight": 40,
                "description": "Self-service checkout systems installed — security review recommended",
                "timestamp": "2026-03-11T15:00:00Z",
            },
        ],
    },
    {
        "address": "53 Sinclair Street, Helensburgh, Glasgow G84 8TG",
        "tenant": "Scandinavian Shop (Glasgow) Ltd",
        "risk_score": 20,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Specialist Import Store",
        "use_mismatch": False,
        "lat": 56.0020,
        "lng": -4.7350,
        "assigned_to": None,
        "signals": [
            {
                "source": "Building Survey",
                "type": "cv_classification",
                "severity": "low",
                "weight": 40,
                "description": "Historic building maintained to high standard — Category B",
                "timestamp": "2026-03-14T10:00:00Z",
            },
        ],
    },
    {
        "address": "9 Bakehouse Close, Edinburgh EH8 8DD",
        "tenant": "Wordsmith AI Ltd",
        "risk_score": 32,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business (Software/IT)",
        "detected_use": "Legal AI Platform",
        "use_mismatch": False,
        "lat": 55.9560,
        "lng": -3.1850,
        "assigned_to": None,
        "signals": [
            {
                "source": "Vision Model",
                "type": "cv_classification",
                "severity": "critical",
                "weight": 40,
                "description": "CV shows 'aparthotel' but property class is 'Office' — potential data error",
                "timestamp": "2026-03-14T12:00:00Z",
            },
            {
                "source": "Street View",
                "type": "keyword_hit",
                "severity": "medium",
                "weight": 15,
                "description": "Significant discoloration on lower wall, vegetation growth noted",
                "timestamp": "2026-03-14T12:00:00Z",
            },
        ],
    },
]


async def seed():
    await init_db()
    async with async_session() as db:
        # Create default insurer
        insurer = Insurer(name="Glasgow Commercial Insurance Ltd")
        db.add(insurer)
        await db.flush()

        for bdata in BUILDINGS:
            building = Building(
                insurer_id=insurer.id,
                address=bdata["address"],
                property_class=bdata["property_class"],
                property_type=bdata["property_type"],
                tenant=bdata["tenant"],
                registered_use=bdata["registered_use"],
                detected_use=bdata["detected_use"],
                use_mismatch=bdata["use_mismatch"],
                listed=bdata["listed"],
                assigned_to=bdata["assigned_to"],
                lat=bdata["lat"],
                lng=bdata["lng"],
                status=bdata["status"],
                risk_score=bdata["risk_score"],
                risk_tier=bdata["risk_tier"],
            )
            db.add(building)
            await db.flush()

            # Create snapshot with evidence items
            snapshot = Snapshot(
                building_id=building.id,
                risk_score=bdata["risk_score"],
                risk_tier=bdata["risk_tier"],
            )
            db.add(snapshot)
            await db.flush()

            for sig in bdata["signals"]:
                evidence = EvidenceItem(
                    snapshot_id=snapshot.id,
                    signal_type=sig["type"],
                    description=sig["description"],
                    weight=sig["weight"],
                    raw_data={"source": sig["source"], "severity": sig["severity"]},
                )
                db.add(evidence)

        await db.commit()
        print(f"Seeded {len(BUILDINGS)} real Glasgow businesses with signals.")


if __name__ == "__main__":
    asyncio.run(seed())
