"""Seed the database with the 20 mock Glasgow buildings and their signals."""
import asyncio
from datetime import datetime

from app.database import init_db, async_session
from app.models.insurer import Insurer
from app.models.building import Building
from app.models.snapshot import Snapshot
from app.models.evidence_item import EvidenceItem


BUILDINGS = [
    {
        "address": "142 Union Street, Glasgow G1 3QQ",
        "tenant": "VapeWorld Glasgow Ltd",
        "risk_score": 94,
        "risk_tier": "critical",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail (Newsagent)",
        "detected_use": "Vape & E-Cigarette Shop",
        "use_mismatch": True,
        "lat": 55.8592,
        "lng": -4.2584,
        "assigned_to": "me",
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "critical", "weight": 40,
             "description": "Detected use mismatch — storefront classified as vape/e-cigarette retail, registered as newsagent",
             "timestamp": "2026-03-14T08:12:00Z"},
            {"source": "Council Rates", "type": "keyword_hit", "severity": "critical", "weight": 15,
             "description": "Unpaid non-domestic rates — £12,400 outstanding since Q3 2025",
             "timestamp": "2026-03-12T14:30:00Z"},
            {"source": "Companies House", "type": "sic_mismatch", "severity": "high", "weight": 25,
             "description": "Ownership transfer recorded — new director appointed 6 weeks ago, prior company dissolved",
             "timestamp": "2026-03-01T09:00:00Z"},
            {"source": "Street View", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Signage change detected — previous tenant branding removed, new unregistered signage",
             "timestamp": "2026-02-28T11:45:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "No fire safety certificate on file for current occupant",
             "timestamp": "2026-02-20T16:00:00Z"},
        ],
    },
    {
        "address": "88 Buchanan Street, Glasgow G1 2FF",
        "tenant": "Highland Brew Coffee Co",
        "risk_score": 72,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Café / Coffee Shop",
        "use_mismatch": False,
        "lat": 55.8611,
        "lng": -4.2513,
        "assigned_to": None,
        "signals": [
            {"source": "Building Survey", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Listed building — unauthorised external alterations detected on Category B facade",
             "timestamp": "2026-03-13T16:45:00Z"},
            {"source": "Council Planning", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Retrospective planning application submitted for extraction system installation",
             "timestamp": "2026-03-10T10:15:00Z"},
            {"source": "Street View", "type": "cv_classification", "severity": "medium", "weight": 40,
             "description": "External seating area exceeds licensed pavement area by approximately 4m²",
             "timestamp": "2026-02-25T09:30:00Z"},
        ],
    },
    {
        "address": "15 Sauchiehall Street, Glasgow G2 3AT",
        "tenant": "CloudSpace Co-Working",
        "risk_score": 68,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Co-Working / Events Space",
        "use_mismatch": True,
        "lat": 55.8651,
        "lng": -4.2574,
        "assigned_to": "me",
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Partial use as events venue detected — not covered under current Class 4 designation",
             "timestamp": "2026-03-13T11:20:00Z"},
            {"source": "Licensing Board", "type": "licensing", "severity": "medium", "weight": 20,
             "description": "Occasional alcohol license granted — not reflected in policy terms",
             "timestamp": "2026-03-05T14:00:00Z"},
        ],
    },
    {
        "address": "201 Argyle Street, Glasgow G2 8BU",
        "tenant": "MacGregor & Sons Solicitors",
        "risk_score": 45,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Office",
        "property_class": "Office",
        "listed": True,
        "registered_use": "Class 4 — Business",
        "detected_use": "Legal Office",
        "use_mismatch": False,
        "lat": 55.8582,
        "lng": -4.2615,
        "assigned_to": None,
        "signals": [
            {"source": "Building Survey", "type": "cv_classification", "severity": "medium", "weight": 40,
             "description": "Minor stonework deterioration noted on listed facade — recommend monitoring",
             "timestamp": "2026-03-12T09:30:00Z"},
            {"source": "Flood Risk", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Property within 200m of River Clyde — SEPA flood risk zone B",
             "timestamp": "2026-02-15T12:00:00Z"},
        ],
    },
    {
        "address": "33 Gordon Street, Glasgow G1 3PF",
        "tenant": "Zenith Fitness Studio",
        "risk_score": 58,
        "risk_tier": "medium",
        "status": "needs_review",
        "property_type": "Leisure",
        "property_class": "Leisure",
        "listed": False,
        "registered_use": "Class 11 — Assembly & Leisure",
        "detected_use": "Gym / Fitness Studio",
        "use_mismatch": False,
        "lat": 55.8601,
        "lng": -4.2556,
        "assigned_to": None,
        "signals": [
            {"source": "Health & Safety", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Basement gym area — ventilation compliance certificate expired Feb 2026",
             "timestamp": "2026-03-11T15:00:00Z"},
            {"source": "Council Rates", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "Rateable value reassessment pending — increase expected",
             "timestamp": "2026-03-01T08:00:00Z"},
        ],
    },
    {
        "address": "7 Royal Exchange Square, Glasgow G1 3AJ",
        "tenant": "Finch & Sparrow Interiors",
        "risk_score": 31,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Interior Design Showroom",
        "use_mismatch": False,
        "lat": 55.8596,
        "lng": -4.2504,
        "assigned_to": None,
        "signals": [
            {"source": "Building Survey", "type": "cv_classification", "severity": "low", "weight": 40,
             "description": "Listed building in good condition — Category A, no concerns raised",
             "timestamp": "2026-03-10T10:00:00Z"},
        ],
    },
    {
        "address": "56 West Nile Street, Glasgow G1 2NP",
        "tenant": "Pixel & Byte Digital Agency",
        "risk_score": 22,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Digital Agency Office",
        "use_mismatch": False,
        "lat": 55.8628,
        "lng": -4.2548,
        "assigned_to": None,
        "signals": [
            {"source": "Routine Check", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "All compliance documents current — next review due Q2 2026",
             "timestamp": "2026-03-09T14:30:00Z"},
        ],
    },
    {
        "address": "120 Trongate, Glasgow G1 5ES",
        "tenant": "Glasgow Print Workshop",
        "risk_score": 41,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Industrial",
        "property_class": "Industrial",
        "listed": True,
        "registered_use": "Class 5 — General Industrial",
        "detected_use": "Print Workshop / Gallery",
        "use_mismatch": False,
        "lat": 55.8563,
        "lng": -4.2441,
        "assigned_to": "me",
        "signals": [
            {"source": "Environmental Health", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Chemical storage noted — COSHH assessment due for renewal",
             "timestamp": "2026-03-08T11:00:00Z"},
            {"source": "Building Survey", "type": "cv_classification", "severity": "low", "weight": 40,
             "description": "Listed building — minor internal modifications approved by Historic Scotland",
             "timestamp": "2026-02-01T10:00:00Z"},
        ],
    },
    {
        "address": "5 Bothwell Street, Glasgow G2 6NL",
        "tenant": "Clyde Valley Insurance Brokers",
        "risk_score": 18,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Insurance Brokerage",
        "use_mismatch": False,
        "lat": 55.8608,
        "lng": -4.2602,
        "assigned_to": None,
        "signals": [
            {"source": "Routine Check", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "All compliance documents current — fully compliant, low risk",
             "timestamp": "2026-03-07T09:00:00Z"},
        ],
    },
    {
        "address": "310 Clyde Street, Glasgow G1 4NP",
        "tenant": "Riverside Storage Solutions",
        "risk_score": 53,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Warehouse",
        "property_class": "Warehouse",
        "listed": False,
        "registered_use": "Class 6 — Storage & Distribution",
        "detected_use": "Self-Storage Facility",
        "use_mismatch": False,
        "lat": 55.8545,
        "lng": -4.2522,
        "assigned_to": None,
        "signals": [
            {"source": "Flood Risk", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Adjacent to River Clyde — within SEPA 1-in-200 year flood zone",
             "timestamp": "2026-03-06T16:30:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Fire risk assessment overdue — last inspection recorded 18 months ago",
             "timestamp": "2026-02-10T13:00:00Z"},
        ],
    },
    {
        "address": "22 Mitchell Lane, Glasgow G1 3NU",
        "tenant": "The Lighthouse Gallery",
        "risk_score": 35,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Leisure",
        "property_class": "Leisure",
        "listed": True,
        "registered_use": "Class 11 — Assembly & Leisure",
        "detected_use": "Art Gallery / Exhibition Space",
        "use_mismatch": False,
        "lat": 55.8604,
        "lng": -4.2530,
        "assigned_to": None,
        "signals": [
            {"source": "Building Survey", "type": "cv_classification", "severity": "low", "weight": 40,
             "description": "Category A listed — condition excellent, recent restoration completed",
             "timestamp": "2026-03-05T12:00:00Z"},
        ],
    },
    {
        "address": "48 Virginia Street, Glasgow G1 1TY",
        "tenant": "Merchant City Dental Practice",
        "risk_score": 62,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Healthcare",
        "property_class": "Healthcare",
        "listed": True,
        "registered_use": "Class 2 — Financial & Professional",
        "detected_use": "Dental Surgery",
        "use_mismatch": True,
        "lat": 55.8575,
        "lng": -4.2470,
        "assigned_to": "me",
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Use mismatch — registered as financial/professional services, operating as dental surgery",
             "timestamp": "2026-03-13T13:00:00Z"},
            {"source": "Environmental Health", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Clinical waste disposal contract not on file — requires verification",
             "timestamp": "2026-03-08T10:00:00Z"},
            {"source": "Building Survey", "type": "cv_classification", "severity": "low", "weight": 40,
             "description": "Listed building — internal modifications for clinical use may require consent",
             "timestamp": "2026-02-18T14:00:00Z"},
        ],
    },
    {
        "address": "95 Hope Street, Glasgow G2 6LD",
        "tenant": "Neon Nails & Beauty Bar",
        "risk_score": 87,
        "risk_tier": "critical",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail (Clothing)",
        "detected_use": "Nail Salon / Beauty Services",
        "use_mismatch": True,
        "lat": 55.8620,
        "lng": -4.2570,
        "assigned_to": None,
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "critical", "weight": 40,
             "description": "Significant use mismatch — registered as clothing retail, operating as nail/beauty salon with chemical treatments",
             "timestamp": "2026-03-14T06:30:00Z"},
            {"source": "Health & Safety", "type": "keyword_hit", "severity": "critical", "weight": 15,
             "description": "Ventilation system inadequate for chemical nail treatments — potential COSHH breach",
             "timestamp": "2026-03-12T09:00:00Z"},
            {"source": "Companies House", "type": "sic_mismatch", "severity": "high", "weight": 25,
             "description": "Company registered 3 weeks ago — single director, no prior trading history in UK",
             "timestamp": "2026-03-05T11:00:00Z"},
            {"source": "Council Rates", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Business rates category not updated to reflect change of use",
             "timestamp": "2026-02-28T14:00:00Z"},
        ],
    },
    {
        "address": "180 St Vincent Street, Glasgow G2 5SG",
        "tenant": "Atlas Wealth Management",
        "risk_score": 28,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Office",
        "property_class": "Office",
        "listed": False,
        "registered_use": "Class 4 — Business",
        "detected_use": "Financial Advisory Office",
        "use_mismatch": False,
        "lat": 55.8615,
        "lng": -4.2630,
        "assigned_to": None,
        "signals": [
            {"source": "Routine Check", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "Fully compliant — FCA registration verified, all documents current",
             "timestamp": "2026-03-11T10:00:00Z"},
        ],
    },
    {
        "address": "12 King Street, Glasgow G1 5QP",
        "tenant": "Clyde Kebab House",
        "risk_score": 76,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink",
        "detected_use": "Late-Night Takeaway",
        "use_mismatch": True,
        "lat": 55.8568,
        "lng": -4.2458,
        "assigned_to": None,
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Operating as late-night takeaway — not covered under Class 3 food & drink designation",
             "timestamp": "2026-03-14T02:15:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Extraction system not compliant — grease build-up noted in ductwork during spot check",
             "timestamp": "2026-03-10T19:00:00Z"},
            {"source": "Licensing Board", "type": "licensing", "severity": "medium", "weight": 20,
             "description": "Late-night opening hours exceed license — operating until 4am, licensed until 11pm",
             "timestamp": "2026-03-06T23:30:00Z"},
        ],
    },
    {
        "address": "60 Jamaica Street, Glasgow G1 4QG",
        "tenant": "Quick Cash Pawnbrokers",
        "risk_score": 91,
        "risk_tier": "critical",
        "status": "needs_review",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": False,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Pawnbroker / Money Transfer",
        "use_mismatch": True,
        "lat": 55.8558,
        "lng": -4.2565,
        "assigned_to": "me",
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "critical", "weight": 40,
             "description": "Multiple undisclosed services detected — pawnbroking, money transfer, pay-day loans from single premises",
             "timestamp": "2026-03-14T07:45:00Z"},
            {"source": "Companies House", "type": "sic_mismatch", "severity": "critical", "weight": 25,
             "description": "Three company dissolutions at this address in 24 months — phoenix trading pattern suspected",
             "timestamp": "2026-03-11T08:00:00Z"},
            {"source": "Council Rates", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Outstanding rates of £8,200 — county court judgement registered",
             "timestamp": "2026-03-02T12:00:00Z"},
            {"source": "Health & Safety", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Security shutters not compliant with fire egress requirements",
             "timestamp": "2026-02-22T15:00:00Z"},
        ],
    },
    {
        "address": "250 George Street, Glasgow G1 1QX",
        "tenant": "Morrison Academy of Music",
        "risk_score": 42,
        "risk_tier": "medium",
        "status": "monitoring",
        "property_type": "Leisure",
        "property_class": "Leisure",
        "listed": True,
        "registered_use": "Class 11 — Assembly & Leisure",
        "detected_use": "Music School / Rehearsal Space",
        "use_mismatch": False,
        "lat": 55.8640,
        "lng": -4.2500,
        "assigned_to": None,
        "signals": [
            {"source": "Building Survey", "type": "cv_classification", "severity": "medium", "weight": 40,
             "description": "Sound insulation between units below standard — complaint from adjacent occupier",
             "timestamp": "2026-03-09T16:00:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "Fire doors on second floor require adjustment — minor non-compliance",
             "timestamp": "2026-02-20T10:00:00Z"},
        ],
    },
    {
        "address": "35 Bath Street, Glasgow G2 1HW",
        "tenant": "Strathclyde Smoke Lounge",
        "risk_score": 82,
        "risk_tier": "high",
        "status": "needs_review",
        "property_type": "Leisure",
        "property_class": "Leisure",
        "listed": False,
        "registered_use": "Class 3 — Food & Drink (Bar)",
        "detected_use": "Shisha Lounge / Hookah Bar",
        "use_mismatch": True,
        "lat": 55.8635,
        "lng": -4.2555,
        "assigned_to": None,
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "high", "weight": 40,
             "description": "Operating as shisha/hookah lounge — significant fire and ventilation risk not covered by bar classification",
             "timestamp": "2026-03-13T20:00:00Z"},
            {"source": "Environmental Health", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Indoor smoking detected — potential breach of Smoking, Health and Social Care Act 2005",
             "timestamp": "2026-03-10T22:00:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "high", "weight": 15,
             "description": "Charcoal heating elements in use — fire risk assessment not updated to reflect hookah operations",
             "timestamp": "2026-03-07T14:00:00Z"},
        ],
    },
    {
        "address": "14 Candleriggs, Glasgow G1 1LD",
        "tenant": "Merchant City Vintage",
        "risk_score": 19,
        "risk_tier": "low",
        "status": "cleared",
        "property_type": "Retail",
        "property_class": "Retail",
        "listed": True,
        "registered_use": "Class 1 — Retail",
        "detected_use": "Vintage Clothing Store",
        "use_mismatch": False,
        "lat": 55.8583,
        "lng": -4.2462,
        "assigned_to": None,
        "signals": [
            {"source": "Routine Check", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "All compliance documents verified — Category B listed building in excellent condition",
             "timestamp": "2026-03-08T09:00:00Z"},
        ],
    },
    {
        "address": "77 Renfield Street, Glasgow G2 1LP",
        "tenant": "SkyBet Gaming Lounge",
        "risk_score": 88,
        "risk_tier": "critical",
        "status": "needs_review",
        "property_type": "Leisure",
        "property_class": "Leisure",
        "listed": False,
        "registered_use": "Class 11 — Assembly & Leisure",
        "detected_use": "Unlicensed Gaming Premises",
        "use_mismatch": True,
        "lat": 55.8625,
        "lng": -4.2540,
        "assigned_to": "me",
        "signals": [
            {"source": "Vision Model", "type": "cv_classification", "severity": "critical", "weight": 40,
             "description": "Fixed-odds betting terminals detected — premises not licensed by Gambling Commission for this category",
             "timestamp": "2026-03-14T09:00:00Z"},
            {"source": "Licensing Board", "type": "licensing", "severity": "critical", "weight": 20,
             "description": "Operating without Gambling Commission premises license — enforcement notice pending",
             "timestamp": "2026-03-12T11:00:00Z"},
            {"source": "Companies House", "type": "sic_mismatch", "severity": "high", "weight": 25,
             "description": "Company registered to overseas holding — beneficial ownership unclear",
             "timestamp": "2026-03-08T09:00:00Z"},
            {"source": "Fire Service", "type": "keyword_hit", "severity": "medium", "weight": 15,
             "description": "Emergency exit partially blocked by gaming machines — access width below minimum",
             "timestamp": "2026-03-04T16:00:00Z"},
            {"source": "Council Rates", "type": "keyword_hit", "severity": "low", "weight": 15,
             "description": "Rateable value under review following change of use",
             "timestamp": "2026-02-25T10:00:00Z"},
        ],
    },
]


async def seed():
    await init_db()
    async with async_session() as db:
        # Create default insurer
        insurer = Insurer(name="Glasgow Commercial Insurance Ltd")
        db.add(insurer)
        await db.flush()

        for bdata in BUILDINGS:
            building = Building(
                insurer_id=insurer.id,
                address=bdata["address"],
                property_class=bdata["property_class"],
                property_type=bdata["property_type"],
                tenant=bdata["tenant"],
                registered_use=bdata["registered_use"],
                detected_use=bdata["detected_use"],
                use_mismatch=bdata["use_mismatch"],
                listed=bdata["listed"],
                assigned_to=bdata["assigned_to"],
                lat=bdata["lat"],
                lng=bdata["lng"],
                status=bdata["status"],
                risk_score=bdata["risk_score"],
                risk_tier=bdata["risk_tier"],
            )
            db.add(building)
            await db.flush()

            # Create snapshot with evidence items
            snapshot = Snapshot(
                building_id=building.id,
                risk_score=bdata["risk_score"],
                risk_tier=bdata["risk_tier"],
            )
            db.add(snapshot)
            await db.flush()

            for sig in bdata["signals"]:
                evidence = EvidenceItem(
                    snapshot_id=snapshot.id,
                    signal_type=sig["type"],
                    description=sig["description"],
                    weight=sig["weight"],
                    raw_data={"source": sig["source"], "severity": sig["severity"]},
                )
                db.add(evidence)

        await db.commit()
        print(f"Seeded {len(BUILDINGS)} buildings with signals.")


if __name__ == "__main__":
    asyncio.run(seed())
