import type { Building } from "./types";

export const buildings: Building[] = [
  {
    id: "b1",
    address: "142 Union Street, Glasgow G1 3QQ",
    tenant: "VapeWorld Glasgow Ltd",
    riskScore: 94,
    riskTrend: "up",
    riskTier: "critical",
    status: "needs_review",
    propertyType: "Retail",
    listed: false,
    registeredUse: "Class 1 — Retail (Newsagent)",
    detectedUse: "Vape & E-Cigarette Shop",
    useMismatch: true,
    lat: 55.8592,
    lng: -4.2584,
    lastUpdated: "2026-03-14T08:12:00Z",
    assignedTo: "me",
    signals: [
      {
        id: "s1a",
        source: "Vision Model",
        severity: "critical",
        description:
          "Detected use mismatch — storefront classified as vape/e-cigarette retail, registered as newsagent",
        timestamp: "2026-03-14T08:12:00Z",
      },
      {
        id: "s1b",
        source: "Council Rates",
        severity: "critical",
        description:
          "Unpaid non-domestic rates — £12,400 outstanding since Q3 2025",
        timestamp: "2026-03-12T14:30:00Z",
      },
      {
        id: "s1c",
        source: "Companies House",
        severity: "high",
        description:
          "Ownership transfer recorded — new director appointed 6 weeks ago, prior company dissolved",
        timestamp: "2026-03-01T09:00:00Z",
      },
      {
        id: "s1d",
        source: "Street View",
        severity: "high",
        description:
          "Signage change detected — previous tenant branding removed, new unregistered signage",
        timestamp: "2026-02-28T11:45:00Z",
      },
      {
        id: "s1e",
        source: "Fire Service",
        severity: "medium",
        description:
          "No fire safety certificate on file for current occupant",
        timestamp: "2026-02-20T16:00:00Z",
      },
    ],
  },
  {
    id: "b2",
    address: "88 Buchanan Street, Glasgow G1 2FF",
    tenant: "Highland Brew Coffee Co",
    riskScore: 72,
    riskTrend: "up",
    riskTier: "high",
    status: "needs_review",
    propertyType: "Retail",
    listed: true,
    registeredUse: "Class 3 — Food & Drink",
    detectedUse: "Café / Coffee Shop",
    useMismatch: false,
    lat: 55.8611,
    lng: -4.2513,
    lastUpdated: "2026-03-13T16:45:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s2a",
        source: "Building Survey",
        severity: "high",
        description:
          "Listed building — unauthorised external alterations detected on Category B facade",
        timestamp: "2026-03-13T16:45:00Z",
      },
      {
        id: "s2b",
        source: "Council Planning",
        severity: "high",
        description:
          "Retrospective planning application submitted for extraction system installation",
        timestamp: "2026-03-10T10:15:00Z",
      },
      {
        id: "s2c",
        source: "Street View",
        severity: "medium",
        description:
          "External seating area exceeds licensed pavement area by approximately 4m²",
        timestamp: "2026-02-25T09:30:00Z",
      },
    ],
  },
  {
    id: "b3",
    address: "15 Sauchiehall Street, Glasgow G2 3AT",
    tenant: "CloudSpace Co-Working",
    riskScore: 68,
    riskTrend: "stable",
    riskTier: "high",
    status: "needs_review",
    propertyType: "Office",
    listed: false,
    registeredUse: "Class 4 — Business",
    detectedUse: "Co-Working / Events Space",
    useMismatch: true,
    lat: 55.8651,
    lng: -4.2574,
    lastUpdated: "2026-03-13T11:20:00Z",
    assignedTo: "me",
    signals: [
      {
        id: "s3a",
        source: "Vision Model",
        severity: "high",
        description:
          "Partial use as events venue detected — not covered under current Class 4 designation",
        timestamp: "2026-03-13T11:20:00Z",
      },
      {
        id: "s3b",
        source: "Licensing Board",
        severity: "medium",
        description:
          "Occasional alcohol license granted — not reflected in policy terms",
        timestamp: "2026-03-05T14:00:00Z",
      },
    ],
  },
  {
    id: "b4",
    address: "201 Argyle Street, Glasgow G2 8BU",
    tenant: "MacGregor & Sons Solicitors",
    riskScore: 45,
    riskTrend: "down",
    riskTier: "medium",
    status: "needs_review",
    propertyType: "Office",
    listed: true,
    registeredUse: "Class 4 — Business",
    detectedUse: "Legal Office",
    useMismatch: false,
    lat: 55.8582,
    lng: -4.2615,
    lastUpdated: "2026-03-12T09:30:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s4a",
        source: "Building Survey",
        severity: "medium",
        description:
          "Minor stonework deterioration noted on listed facade — recommend monitoring",
        timestamp: "2026-03-12T09:30:00Z",
      },
      {
        id: "s4b",
        source: "Flood Risk",
        severity: "medium",
        description:
          "Property within 200m of River Clyde — SEPA flood risk zone B",
        timestamp: "2026-02-15T12:00:00Z",
      },
    ],
  },
  {
    id: "b5",
    address: "33 Gordon Street, Glasgow G1 3PF",
    tenant: "Zenith Fitness Studio",
    riskScore: 58,
    riskTrend: "up",
    riskTier: "medium",
    status: "needs_review",
    propertyType: "Leisure",
    listed: false,
    registeredUse: "Class 11 — Assembly & Leisure",
    detectedUse: "Gym / Fitness Studio",
    useMismatch: false,
    lat: 55.8601,
    lng: -4.2556,
    lastUpdated: "2026-03-11T15:00:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s5a",
        source: "Health & Safety",
        severity: "medium",
        description:
          "Basement gym area — ventilation compliance certificate expired Feb 2026",
        timestamp: "2026-03-11T15:00:00Z",
      },
      {
        id: "s5b",
        source: "Council Rates",
        severity: "low",
        description: "Rateable value reassessment pending — increase expected",
        timestamp: "2026-03-01T08:00:00Z",
      },
    ],
  },
  {
    id: "b6",
    address: "7 Royal Exchange Square, Glasgow G1 3AJ",
    tenant: "Finch & Sparrow Interiors",
    riskScore: 31,
    riskTrend: "stable",
    riskTier: "low",
    status: "cleared",
    propertyType: "Retail",
    listed: true,
    registeredUse: "Class 1 — Retail",
    detectedUse: "Interior Design Showroom",
    useMismatch: false,
    lat: 55.8596,
    lng: -4.2504,
    lastUpdated: "2026-03-10T10:00:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s6a",
        source: "Building Survey",
        severity: "low",
        description:
          "Listed building in good condition — Category A, no concerns raised",
        timestamp: "2026-03-10T10:00:00Z",
      },
    ],
  },
  {
    id: "b7",
    address: "56 West Nile Street, Glasgow G1 2NP",
    tenant: "Pixel & Byte Digital Agency",
    riskScore: 22,
    riskTrend: "down",
    riskTier: "low",
    status: "cleared",
    propertyType: "Office",
    listed: false,
    registeredUse: "Class 4 — Business",
    detectedUse: "Digital Agency Office",
    useMismatch: false,
    lat: 55.8628,
    lng: -4.2548,
    lastUpdated: "2026-03-09T14:30:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s7a",
        source: "Routine Check",
        severity: "low",
        description:
          "All compliance documents current — next review due Q2 2026",
        timestamp: "2026-03-09T14:30:00Z",
      },
    ],
  },
  {
    id: "b8",
    address: "120 Trongate, Glasgow G1 5ES",
    tenant: "Glasgow Print Workshop",
    riskScore: 41,
    riskTrend: "stable",
    riskTier: "medium",
    status: "monitoring",
    propertyType: "Industrial",
    listed: true,
    registeredUse: "Class 5 — General Industrial",
    detectedUse: "Print Workshop / Gallery",
    useMismatch: false,
    lat: 55.8563,
    lng: -4.2441,
    lastUpdated: "2026-03-08T11:00:00Z",
    assignedTo: "me",
    signals: [
      {
        id: "s8a",
        source: "Environmental Health",
        severity: "medium",
        description:
          "Chemical storage noted — COSHH assessment due for renewal",
        timestamp: "2026-03-08T11:00:00Z",
      },
      {
        id: "s8b",
        source: "Building Survey",
        severity: "low",
        description:
          "Listed building — minor internal modifications approved by Historic Scotland",
        timestamp: "2026-02-01T10:00:00Z",
      },
    ],
  },
  {
    id: "b9",
    address: "5 Bothwell Street, Glasgow G2 6NL",
    tenant: "Clyde Valley Insurance Brokers",
    riskScore: 18,
    riskTrend: "down",
    riskTier: "low",
    status: "cleared",
    propertyType: "Office",
    listed: false,
    registeredUse: "Class 4 — Business",
    detectedUse: "Insurance Brokerage",
    useMismatch: false,
    lat: 55.8608,
    lng: -4.2602,
    lastUpdated: "2026-03-07T09:00:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s9a",
        source: "Routine Check",
        severity: "low",
        description:
          "All compliance documents current — fully compliant, low risk",
        timestamp: "2026-03-07T09:00:00Z",
      },
    ],
  },
  {
    id: "b10",
    address: "310 Clyde Street, Glasgow G1 4NP",
    tenant: "Riverside Storage Solutions",
    riskScore: 53,
    riskTrend: "up",
    riskTier: "medium",
    status: "monitoring",
    propertyType: "Warehouse",
    listed: false,
    registeredUse: "Class 6 — Storage & Distribution",
    detectedUse: "Self-Storage Facility",
    useMismatch: false,
    lat: 55.8545,
    lng: -4.2522,
    lastUpdated: "2026-03-06T16:30:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s10a",
        source: "Flood Risk",
        severity: "high",
        description:
          "Adjacent to River Clyde — within SEPA 1-in-200 year flood zone",
        timestamp: "2026-03-06T16:30:00Z",
      },
      {
        id: "s10b",
        source: "Fire Service",
        severity: "medium",
        description:
          "Fire risk assessment overdue — last inspection recorded 18 months ago",
        timestamp: "2026-02-10T13:00:00Z",
      },
    ],
  },
  {
    id: "b11",
    address: "22 Mitchell Lane, Glasgow G1 3NU",
    tenant: "The Lighthouse Gallery",
    riskScore: 35,
    riskTrend: "stable",
    riskTier: "low",
    status: "cleared",
    propertyType: "Leisure",
    listed: true,
    registeredUse: "Class 11 — Assembly & Leisure",
    detectedUse: "Art Gallery / Exhibition Space",
    useMismatch: false,
    lat: 55.8604,
    lng: -4.2530,
    lastUpdated: "2026-03-05T12:00:00Z",
    assignedTo: null,
    signals: [
      {
        id: "s11a",
        source: "Building Survey",
        severity: "low",
        description:
          "Category A listed — condition excellent, recent restoration completed",
        timestamp: "2026-03-05T12:00:00Z",
      },
    ],
  },
  {
    id: "b12",
    address: "48 Virginia Street, Glasgow G1 1TY",
    tenant: "Merchant City Dental Practice",
    riskScore: 62,
    riskTrend: "up",
    riskTier: "high",
    status: "needs_review",
    propertyType: "Healthcare",
    listed: true,
    registeredUse: "Class 2 — Financial & Professional",
    detectedUse: "Dental Surgery",
    useMismatch: true,
    lat: 55.8575,
    lng: -4.2470,
    lastUpdated: "2026-03-13T13:00:00Z",
    assignedTo: "me",
    signals: [
      {
        id: "s12a",
        source: "Vision Model",
        severity: "high",
        description:
          "Use mismatch — registered as financial/professional services, operating as dental surgery",
        timestamp: "2026-03-13T13:00:00Z",
      },
      {
        id: "s12b",
        source: "Environmental Health",
        severity: "medium",
        description:
          "Clinical waste disposal contract not on file — requires verification",
        timestamp: "2026-03-08T10:00:00Z",
      },
      {
        id: "s12c",
        source: "Building Survey",
        severity: "low",
        description:
          "Listed building — internal modifications for clinical use may require consent",
        timestamp: "2026-02-18T14:00:00Z",
      },
    ],
  },
];
